apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: deployment
spec:
  selector:
    matchLabels:
      app: deployment
  template:
    spec:
      containers:
      - name: application
        image: application
        envFrom:
        - configMapRef:
            name: config
